import Home from './Home/Home.jsx'
import Search from './search/Search.jsx'
import Logout from './Logout/Logout.jsx'
import Signup from './Signup/Signup.jsx'
import User from './User/User.jsx'
import Users from './Users/Users.jsx'
import Login from './Login/Login.jsx'
import EditImg from './EditImg/EditImg.jsx'
import Follow from './Follow/Follow.jsx'
import Comments from './Comments/Comments.jsx'
export {EditImg,Search,Home,Logout,Users,Comments,Signup,User,Follow,Login}