import Home from './Home/Home.jsx'
import WaitingPosts from './WaitingPosts/WaitingPosts.jsx'
import Search from './search/Search.jsx'
import Logout from './Logout/Logout.jsx'
import Signup from './Signup/Signup.jsx'
import User from './User/User.jsx'
import Users from './Users/Users.jsx'
import Login from './Login/Login.jsx'
import EditImg from './EditImg/EditImg.jsx'
import Follow from './Follow/Follow.jsx'
import CommunityForm from './CommunityForm/CommunityForm.jsx'
import Comments from './Comments/Comments.jsx'
import Community from './Community/Community.jsx'
export {EditImg,WaitingPosts,CommunityForm,Search,Home,Logout,Users,Comments,Community,Signup,User,Follow,Login}